version: "3"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/code
      - /home/node/code/node_modules
    links:
      - mongobox
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongobox:27017
  mongobox:
    image: mongo:4
